import { Card, CardContent } from "@/components/ui/card"

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-3xl">
      <h1 className="text-4xl font-bold text-foreground mb-8">Terms of Service</h1>

      <Card className="border-primary/20 bg-background/40 backdrop-blur-md">
        <CardContent className="space-y-6 text-muted-foreground leading-relaxed pt-6">
          <p>Last Updated: {new Date().toLocaleDateString()}</p>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using PolicyParser, you accept and agree to be bound by the terms and provision of this agreement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">2. Disclaimer of Advice</h2>
            <div className="p-4 bg-amber-900/20 border border-amber-900/50 rounded-lg">
              <p className="text-amber-200 font-medium">
                PolicyParser is an AI-powered tool for informational purposes only. It does NOT provide legal advice.
              </p>
            </div>
            <p className="mt-4">
              The summaries, risk assessments, and insights generated by this tool are automated and may contain errors. You should not rely on this tool as a substitute for professional legal counsel. Always read the original documents and consult with a qualified attorney for legal matters.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">3. Use of Service</h2>
            <p>
              You agree not to use this service for any unlawful purpose. You are responsible for ensuring that you have the right to upload and analyze any documents you submit.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">4. Limitation of Liability</h2>
            <p>
              In no event shall PolicyParser be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of this website or the information provided herein.
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  )
}
